version: "3.7"

services:

  postgres:
    container_name: 'di-container-java'
    image: 'postgres:latest'
    restart: always
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=username'
      - 'POSTGRES_DB=kindergarten'
      - 'POSTGRES_PASSWORD=password'

